### ISSUE TITLE
ISBAT use a Masonry Gallery block that is not based on masonry.desandro.com

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#2078]
### Describe the bug:

There are a number of open issues on CoBlocks related to UX concerns of the Masonry gallery block. One of our main issues with the Masonry gallery block is that sometimes the images do not render correctly in a masonry layout especially in a mobile view.

We should consider another 3rd party library that will allow us to achieve a masonry layout usable with the Masonry Gallery block.

We should match all of these criteria when the block has been refactored into a new library.
- [x] <del>[ISBAT sort images in Masonry Gallery - Something like ascending, descending by upload date, or random, or append to top or bottom.](https://github.com/godaddy-wordpress/coblocks/issues/1890)</del>
  - This is a complicated feature and should be handled in a future iteration.
- [x] [ISBAT have a variety of image size display options available to users](https://github.com/godaddy-wordpress/coblocks/issues/1756) - (400px, 1200px etc)
- [x] <del>[ISBAT access image replace controls both on image and in block toolbar](https://github.com/godaddy-wordpress/coblocks/issues/1749)</del>
  - Image replace and move controls will not exist presently on the Masonry block. This feature is not mirrored in the new Gallery architecture but may come from the core as the v1 Gallery did.
- [ ] [ISBAT transform into other blocks that have gutter controls](https://github.com/godaddy-wordpress/coblocks/issues/1719)
- [ ] [ISBAT update image captions from within the media library as well as block editor](https://github.com/godaddy-wordpress/coblocks/issues/1620)
- [x] [ISBAT has a mobile view that displays images in a single column](https://github.com/godaddy-wordpress/coblocks/issues/1538)
- [x] [ISN use jQuery in refactored Masonry Gallery](https://github.com/godaddy-wordpress/coblocks/issues/1365)
- [x] <del>[ISB using the newer size controls and deprecated the old controls](https://github.com/godaddy-wordpress/coblocks/issues/1041)</del>
  - Size controls have been deprecated and removed. I think we should consider the fourth masonry column when the block is set to full width.
